### ISSUE TITLE
请问您的mAP是哪个数据集的测试结果？是用的哪一种测量方法？（07voc/12voc/coco0.5/coco0.5：095）

### ISSUE THREAD

**Issue by 1453042287** [zhanghanduo/yolo3_pytorch#3]
您好，因为我最近也在做bdd100k的检测工作，看到您的mAP实在是让我惊讶不已，我所使用的yolo3的backbone是mobilenetv2，但是在bdd100k上的mAP只有35而已，评价标准是使用的voc07的方法

**Comment by 1453042287** [comment]
ok, i saw 'the paper'...

**Comment by zhanghanduo** [comment]
不好意思 这个repo是个自娱自乐的项目，fork自https://github.com/BobLiu20/YOLOv3_PyTorch.git. 所以readme里面的mAP不是Bdd的，因为最近没有在用Bdd，所以可能暂时没法给您参考，不过mobilenetv2做yolo的backbone可能准确度上确实不会太好，paper用的是Darknet自己的backbone

**Comment by 1453042287** [comment]
@zhanghanduo 抱歉再次打扰，不过readme里面的mAP是您自己训练出来的吗？我也尝试用这个模型去在coco2017上训练，但是效果很差

**Comment by zhanghanduo** [comment]
我自己的也不好，没有post上去，很久之前了。这个map不是BDD的结果。这个repo的某些implementation有问题，为了节约你的时间，建议你尝试https://github.com/ultralytics/yolov3之类比较active 的repo，最近我没有在做object detection，没有时间继续研究，不好意思

**Comment by CoreJa** [comment]
@1453042287 您好！我最近也在针对bdd100k研究。同样没有训练出很好的效果。使用的coco0.5:0.95的测量方法，基于yolov3-416，因为时间受限只做了50次epoch，mAP在25左右，想和您讨论一下您mAP是在大概怎样的环境下训练出来的呢以及您后续的一些调整？我针对anchor做了聚类，在尝试做一些可能的改进来优化效果。
希望可以与您交流，不胜感激！

**Comment by 1453042287** [comment]
@Core00077 抱歉我已经有段时间没用过BDD了，当初是想刷下模型性能，BDD比赛用的是voc12的标准，而且IOU是0.7的阈值，当初最多也就刷到20+，后来就没再继续了，如果你单纯是想刷精度的话，用其它的模型的baseline改进会比较好，如果是为了落地的话，据我所知，cvpr19已经有很多检测器在速度和精度两方面碾压yolo3了并且也已经开源了
